language: go
sudo: required

go:
  - 1.11.x
go_import_path: github.com/vaporz/turbo
before_install:
  - ./.travis/install-thrift.sh
  - ./.travis/install-protoc.sh 3.1.0
  - go get github.com/mattn/goveralls
  - go get github.com/vaporz/turbo
  - go install github.com/vaporz/turbo/protoc-gen-buildfields
  - go get github.com/golang/protobuf/protoc-gen-go
  - go install github.com/golang/protobuf/protoc-gen-go

install:
  - go mod vendor

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci -ignore=protoc-gen-buildfields/*,test/testservice/*,test/testservice/*/*,test/testservice/*/*/*,test/testservice/*/*/*/*/*,test/testservice/*/*/*/*/*/*,turbo/*,turbo/cmd/root.go

env:
  global:
  - "PATH=$PATH:$HOME/local/bin"
